### ISSUE TITLE
transit_data_train.pkl

### ISSUE THREAD

**Issue by daz261** [pearsonkyle/Exoplanet-Artificial-Intelligence#1]
I am trying to run generate_data.py, but it doesn't work because there is no pickle_data/transit_data_train.pkl file in the folder. Did you rename it or it's not in the folder?

**Comment by pearsonkyle** [comment]
Hello!
Those pickle files are a little too large to include in the repo so you'll have to generate them yourself. Use this line to create two files: https://github.com/pearsonkyle/Exoplanet-Artificial-Intelligence/blob/master/generate_data.py#L139

You can specify the grid a few lines above that. Be careful about using too sparse of a grid, it might be better to generate samples from a distribution for each parameter.

This example is a little more modern for generating training data: https://github.com/pearsonkyle/Exoplanet-Artificial-Intelligence/blob/master/TESS/cnn_train.py
